### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by overlineink** [splash-ink/studio.splashink.co#1]
Following as defined at [Prototype](https://www.figma.com/proto/QDfbwTjcpjNhOYU0yYuSpRcH/Splash-Ink-Studio?node-id=0%3A1&scaling=scale-down) the custom navbar will be added **aside/left-side** with a relative position on the screen.

- [x] Custom _dark_ theme for Navbar.
**i.e.:** `#0A0909`
- [x] Re-adjust `navbar-size` for small screens with media queries.
```css
@media (max-width: 1366px) {
    .left-sidebar .sidebar-width {
        max-width: 37wv; 
    }
}
```
Aleatory data passed on the i.e. above, just a simple preview.
- [x] Change border color to `#0F0F0F`
- [x] Remove _Digital Studio_ flag to combine with original design defined at [Prototype](https://www.figma.com/proto/QDfbwTjcpjNhOYU0yYuSpRcH/Splash-Ink-Studio?node-id=0%3A1&scaling=scale-down).
