### ISSUE TITLE
Refactor & Test FooterComponent

### ISSUE THREAD

**Issue by overlineink** [splash-ink/studio.splashink.co#4]
Apply some changes at `semibold-font` class at `.\footer\footer.component.css`.
```css
semibold-font {
    font-weight: 600;
    font-size: 13px; /* add this instruction */
}
```

### Unit Test
It should's:
- [x] Contain a `copyright` linked to _www.splashink.co_;
- [x] Contact info match with correct company details;
- [x] Contain a logo;
